spring:
  datasource:
    url: jdbc:mysql://localhost:3306/documents?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password: root  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
       format_sql: true
  servlet:
    multipart:
      max-file-size: 20MB
          